require 'rails_helper'

RSpec.describe Comment, type: :model do

  it 'is invalid factory' do
    FactoryGirl.create(:comment).should be_valid
  end

  it "is valid with description" do
    FactoryGirl.build(:comment, description: 'This spec was generated by rspec-rails when you ran the scaffold generator.
                   It demonstrates how one might use RSpec to specify the controller code that
                   was generated by Rails when you ran the scaffold generator.').should be_valid
  end

  it "is invalid without description" do
    FactoryGirl.build(:comment, description: nil).should_not be_valid
  end

  it "is invalid without minimum description characters 20" do
    description = 'below 20characters'
        FactoryGirl.build(:comment, description: description).should_not be_valid
  end

end
